import type { Metadata } from "next";
import { Lexend  } from "next/font/google";
import "./globals.css";
import { FormularioEventoProvider } from "@/context/FormularioEventoContext";
import { MateriaisProvider } from "@/context/CadastrarMaterialContext";

const lexend = Lexend({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'], 
  variable: '--font-lexend',
});

export const metadata: Metadata = {
  title: "Denzel Eventos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${lexend.variable} font-sans`}> 
        <FormularioEventoProvider>
          <MateriaisProvider>

          {children}
          </MateriaisProvider>
        </FormularioEventoProvider>
        </body>
    </html>
  );
}

